"""policy_settings.txt for a Vietnamese policy scenario.

AgriPoliS iteration t corresponds to simulation period t + 1 (period 1 = 2025).
All scenarios share the S0 baseline until ``policy_start_period``; from then on
the scenario's payments (times its phasing factor) and price multipliers apply.
Payments enter the farm MIP as coupled premiums per hectare of activity.
"""
from __future__ import annotations

from .. import config
from . import economics
from .tables import fmt

POLICY_START_PERIOD = 2        # 2026: first year in which the reviewed reforms can take effect
LAND_ROWS_EQ = "\t".join(f"rhs_row:{lt}=EQ;" for lt in config.LAND_TYPES)


def payments_in_period(scenario_id: str, period: int) -> dict[str, float]:
    if period < POLICY_START_PERIOD:
        return economics.payments_eur("S0_BASELINE")
    factor = economics.payment_factor(scenario_id, period)
    return {c: v * factor for c, v in economics.payments_eur(scenario_id).items()}


def price_multipliers(scenario_id: str, scale: float | None = None) -> dict[str, float]:
    """Price shifts of a scenario; ``scale`` replaces the size of the shift (sensitivity runs)."""
    spec = economics.scenario(scenario_id)
    shifts = {c: m for c, m in (spec.get("price_multipliers") or {}).items() if m != 1.0}
    if scale is not None and shifts:
        largest = max(shifts.values())
        shifts = {c: 1 + (m - 1) * (scale - 1) / (largest - 1) for c, m in shifts.items()}
    return shifts


def policy_lines(scenario_id: str, periods: int, price_scale: float | None = None) -> list[str]:
    lines = ["# generated by hbabm.agripolis_inputs.policy for scenario " + scenario_id]
    previous = None
    for iteration in range(periods):
        period = iteration + 1
        payments = payments_in_period(scenario_id, period)
        block = [f"iteration {iteration}"]
        if payments != previous:
            block.append("\tpremium:\t" + "\t".join(f"{c}={fmt(round(v, 2))};" for c, v in payments.items()))
            previous = payments
        if iteration == 0:
            block.append("\ttranch:\t" + "\t".join(f"tranch_{i}_deg=0;" for i in range(1, 6)))
            block.append("\tothers:\t" + LAND_ROWS_EQ)
        # price_change is a per-period growth factor that stays in force until it is
        # changed: a one-off level shift is the multiplier followed by 1 next period.
        shifts = price_multipliers(scenario_id, price_scale)
        if shifts and period in (POLICY_START_PERIOD, POLICY_START_PERIOD + 1):
            factor = (lambda m: m) if period == POLICY_START_PERIOD else (lambda m: 1)
            block.append("\tprice_change:\t" + "\t".join(f"{c}={factor(round(m, 4))};" for c, m in shifts.items()))
        if len(block) > 1:
            lines += block + [""]
    return lines
