"""policy_settings.txt for a Vietnamese policy scenario.

AgriPoliS iteration t corresponds to simulation period t + 1 (period 1 = 2025).
All scenarios share the S0 baseline until ``policy_start_period``; from then on
the scenario's payments (times its phasing factor) and price multipliers apply.
Payments enter the farm MIP as coupled premiums per hectare of activity.
"""
from __future__ import annotations

from .. import config
from . import economics
from .tables import fmt

POLICY_START_PERIOD = 2        # 2026: first year in which the reviewed reforms can take effect
LAND_ROWS_EQ = "\t".join(f"rhs_row:{lt}=EQ;" for lt in config.LAND_TYPES)


def payments_in_period(scenario_id: str, period: int) -> dict[str, float]:
    if period < POLICY_START_PERIOD:
        return economics.payments_eur("S0_BASELINE")
    factor = economics.payment_factor(scenario_id, period)
    return {c: v * factor for c, v in economics.payments_eur(scenario_id).items()}


def price_multipliers(scenario_id: str) -> dict[str, float]:
    spec = economics.scenario(scenario_id)
    return {c: m for c, m in (spec.get("price_multipliers") or {}).items() if m != 1.0}


def policy_lines(scenario_id: str, periods: int) -> list[str]:
    lines = ["# generated by hbabm.agripolis_inputs.policy for scenario " + scenario_id]
    previous = None
    for iteration in range(periods):
        period = iteration + 1
        payments = payments_in_period(scenario_id, period)
        block = [f"iteration {iteration}"]
        if payments != previous:
            block.append("\tpremium:\t" + "\t".join(f"{c}={fmt(round(v, 2))};" for c, v in payments.items()))
            previous = payments
        if iteration == 0:
            block.append("\ttranch:\t" + "\t".join(f"tranch_{i}_deg=0;" for i in range(1, 6)))
            block.append("\tothers:\t" + LAND_ROWS_EQ)
        if period == POLICY_START_PERIOD and price_multipliers(scenario_id):
            block.append("\tprice_change:\t" + "\t".join(
                f"{c}={m};" for c, m in price_multipliers(scenario_id).items()))
        if len(block) > 1:
            lines += block + [""]
    return lines
