"""Input files of the AgriPoliS social-ecological extension: ses.txt, farm_attributes.txt."""
from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd

from .. import config


@dataclass
class SesOptions:
    awareness: bool = True
    aw_value: float | None = None        # None = value from config/model/ses.json
    feedback: float = 0.0
    ext_coverage: float = 0.0
    ext_effect: float = 0.0
    ext_start: int = 1 << 30
    seed: int | None = None
    overrides: dict = field(default_factory=dict)


def ses_lines(options: SesOptions) -> list[str]:
    spec = config.load_json(config.MODEL_CONFIG_DIR / "ses.json")
    aw = spec["awareness"]
    values = {
        "AWARENESS": "true" if options.awareness else "false",
        "AW_VALUE": options.aw_value if options.aw_value is not None else aw["aw_value_eur_per_ha"],
        "AW_SOCIAL": aw["social_learning"], "AW_RADIUS": aw["radius_plots"],
        "AW_FEEDBACK": options.feedback, "AW_DECAY": aw["decay"],
        "EXT_COVERAGE": options.ext_coverage, "EXT_EFFECT": options.ext_effect, "EXT_START": options.ext_start,
        "NO_EXIT": "true" if spec["no_exit"] else "false",
        "SEED": options.seed if options.seed is not None else spec["seed"],
        **options.overrides,
    }
    lines = ["# generated by hbabm.agripolis_inputs.ses_files"] + [f"{k}\t{v}" for k, v in values.items()]
    lines.append("# ACTIVITY name land_row stewardship max_expand max_contract needs_secure_tenure")
    for code, act in config.activities().items():
        lim = spec["change_limits"][code]
        lines.append(f"ACTIVITY\t{code}\t{act.land_type}\t{int(act.stewardship)}\t{lim['max_expand']}\t"
                     f"{lim['max_contract']}\t{int(lim['secure_tenure'])}")
    return lines


def attribute_lines(managers: pd.DataFrame) -> list[str]:
    lines = ["# farm_name awareness0 asset_index tenure_secure initial_activity (anonymised survey)"]
    for m in managers.itertuples(index=False):
        lines.append(f"{m.manager_id}\t{m.awareness0:.4f}\t{m.asset_index:.4f}\t{int(m.tenure_secure)}\t"
                     f"{m.initial_activity}")
    return lines
